so it sorta works but pip doesnt

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19,56 +19,56 @@
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 # ----- install the Python package -----
-# RWITHPYTHON_PYTHON_VERSION=3.5
-# RWITHPYTHON_PYTHON_VERSION_EXTENDED=3.5.1
-# PYTHON_ARCHIVE_NAME=Python-${RWITHPYTHON_PYTHON_VERSION_EXTENDED}
-# PYTHON_RUNTIME_BUNDLE=https://www.python.org/ftp/python/${RWITHPYTHON_PYTHON_VERSION_EXTENDED}/${PYTHON_ARCHIVE_NAME}.tgz
-# # what follows, delimited by square brackets, is a script to be copied into the 'configure' output file
+RWITHPYTHON_PYTHON_VERSION=3.5
+RWITHPYTHON_PYTHON_VERSION_EXTENDED=3.5.1
+PYTHON_ARCHIVE_NAME=Python-${RWITHPYTHON_PYTHON_VERSION_EXTENDED}
+PYTHON_RUNTIME_BUNDLE=https://www.python.org/ftp/python/${RWITHPYTHON_PYTHON_VERSION_EXTENDED}/${PYTHON_ARCHIVE_NAME}.tgz
+# what follows, delimited by square brackets, is a script to be copied into the 'configure' output file
 
-# cd inst
-# wget -O ${PYTHON_ARCHIVE_NAME}.tgz ${PYTHON_RUNTIME_BUNDLE}
-# if [ "$?" -ne "0" ]; then
-#     curl -o ${PYTHON_ARCHIVE_NAME}.tgz ${PYTHON_RUNTIME_BUNDLE}
-# fi
-# if [ "$?" -ne "0" ]; then
-#   echo "Failed to download ${PYTHON_RUNTIME_BUNDLE}"
-#   exit 1
-# fi
-# gunzip ${PYTHON_ARCHIVE_NAME}.tgz
-# # NOTE: 'gunzip' removes the .tgz file leaving just the .tar file
-# tar -xf ${PYTHON_ARCHIVE_NAME}.tar
-# rm ${PYTHON_ARCHIVE_NAME}.tar
-# RWITHPYTHON_PYTHON_DIR=${PWD}
-# cd ${PYTHON_ARCHIVE_NAME}
-# # in the following line the '--prefix' parameter is the installation location
-# #./configure --enable-shared --prefix=${RWITHPYTHON_PYTHON_DIR}
-# #make
-# #make altinstall
-# cd ..
-# rm -R ${PYTHON_ARCHIVE_NAME}
-# cd ..
+cd inst
+wget -O ${PYTHON_ARCHIVE_NAME}.tgz ${PYTHON_RUNTIME_BUNDLE}
+if [ "$?" -ne "0" ]; then
+    curl -o ${PYTHON_ARCHIVE_NAME}.tgz ${PYTHON_RUNTIME_BUNDLE}
+fi
+if [ "$?" -ne "0" ]; then
+  echo "Failed to download ${PYTHON_RUNTIME_BUNDLE}"
+  exit 1
+fi
+gunzip ${PYTHON_ARCHIVE_NAME}.tgz
+# NOTE: 'gunzip' removes the .tgz file leaving just the .tar file
+tar -xf ${PYTHON_ARCHIVE_NAME}.tar
+rm ${PYTHON_ARCHIVE_NAME}.tar
+RWITHPYTHON_PYTHON_DIR=${PWD}
+cd ${PYTHON_ARCHIVE_NAME}
+# in the following line the '--prefix' parameter is the installation location
+./configure --enable-shared --prefix=${RWITHPYTHON_PYTHON_DIR}
+make
+make altinstall
+cd ..
+rm -R ${PYTHON_ARCHIVE_NAME}
+cd ..
 
-# MYPYTHONCONFIG=${RWITHPYTHON_PYTHON_DIR}/bin/python${RWITHPYTHON_PYTHON_VERSION}m-config
-# MYPYTHON=${RWITHPYTHON_PYTHON_DIR}/bin/python${RWITHPYTHON_PYTHON_VERSION}
+MYPYTHONCONFIG=${RWITHPYTHON_PYTHON_DIR}/bin/python${RWITHPYTHON_PYTHON_VERSION}m-config
+MYPYTHON=${RWITHPYTHON_PYTHON_DIR}/bin/python${RWITHPYTHON_PYTHON_VERSION}
 
-# # Extract the linker and include flags for python
-# : ${PYTHONCONFIG=`which ${MYPYTHONCONFIG}`}
-# if test -z "${PYTHONCONFIG}"; then
-#   echo "could not locate ${MYPYTHONCONFIG}"
-#   exit 1
-# fi
+# Extract the linker and include flags for python
+: ${PYTHONCONFIG=`which ${MYPYTHONCONFIG}`}
+if test -z "${PYTHONCONFIG}"; then
+  echo "could not locate ${MYPYTHONCONFIG}"
+  exit 1
+fi
 
-# # On Mac, after upgrading to 3.5 the following caused: "ld: -stack_size option can only be used when linking a main executable"
-# # So we switch from ldflags to libs
-# #PKG_LIBS=`$PYTHONCONFIG --ldflags`
-# PKG_LIBS=`$PYTHONCONFIG --libs`
+# On Mac, after upgrading to 3.5 the following caused: "ld: -stack_size option can only be used when linking a main executable"
+# So we switch from ldflags to libs
+#PKG_LIBS=`$PYTHONCONFIG --ldflags`
+PKG_LIBS=`$PYTHONCONFIG --libs`
 
-# # PUT the static (not shared) library on the library path
-# PKG_LIBS="-L${RWITHPYTHON_PYTHON_DIR}/lib/python${RWITHPYTHON_PYTHON_VERSION}/config-${RWITHPYTHON_PYTHON_VERSION}m ${PKG_LIBS}"
+# PUT the static (not shared) library on the library path
+PKG_LIBS="-L${RWITHPYTHON_PYTHON_DIR}/lib/python${RWITHPYTHON_PYTHON_VERSION}/config-${RWITHPYTHON_PYTHON_VERSION}m ${PKG_LIBS}"
 
-# PKG_CFLAGS=`$PYTHONCONFIG --includes`
+PKG_CFLAGS=`$PYTHONCONFIG --includes`
 
-USESPECIALPYTHONVERSION=python #./inst/bin/python$RWITHPYTHON_PYTHON_VERSION
+USESPECIALPYTHONVERSION=./inst/bin/python$RWITHPYTHON_PYTHON_VERSION
 
 
 if ! [ -z "$USESPECIALPYTHONVERSION" ]; then
@@ -77,7 +77,7 @@ if ! [ -z "$USESPECIALPYTHONVERSION" ]; then
 fi 
 
 PYVERSION=`python -c "import sys;import distutils.sysconfig as sc;sys.stdout.write(sc.get_config_var('VERSION'))"`
-#PYINCLUDE=`python -c "import sys;import distutils.sysconfig as sc;sys.stdout.write(sc.get_config_var('INCLUDEPY'))"`
+PYINCLUDE=`python -c "import sys;import distutils.sysconfig as sc;sys.stdout.write(sc.get_config_var('INCLUDEPY'))"`
 PYBINPATH=`python -c "import sys;import os;sys.stdout.write(os.path.dirname(sys.executable))"`
 # sys.version_info.major would be a alternative to hexversion
 PY3FLAG=`python -c 'import sys; print("%i" % (sys.hexversion<0x03000000))'`
@@ -90,7 +90,7 @@ echo ""
 if [ $PY3FLAG -eq 0 ]; then
     echo "python version is > 3"
     PYXY="PYTHONLIBXY=libpython"$PYVERSION"m.so"
-    PYLIBS="PKG_LIBS=-L${RWITHPYTHON_PYTHON_DIR}/lib/python${RWITHPYTHON_PYTHON_VERSION}/config-${RWITHPYTHON_PYTHON_VERSION}m "`$PYTHONCONFIG --ldflags`
+    PYLIBS="PKG_LIBS=-L${RWITHPYTHON_PYTHON_DIR}/lib/python${RWITHPYTHON_PYTHON_VERSION}/config-${RWITHPYTHON_PYTHON_VERSION}m "`$PYTHONCONFIG --libs`
     PYCFLAGS="PKG_CFLAGS="`$PYTHONCONFIG --cflags`" -D $PYXY -D PYTHON_IN_R_NO_EXPLICIT_LINKING"
 else 
     echo "python version is < 3"
@@ -98,6 +98,8 @@ else
     PYLIBS="PKG_LIBS="`$PYBINPATH/python$PYVERSIONm-config --ldflags`
     PYCFLAGS="PKG_CFLAGS="`$PYBINPATH/python$PYVERSIONm-config --cflags`" -D $PYXY -D PYTHON_IN_R_NO_EXPLICIT_LINKING"
 fi
+
+./cleanup
 
 echo ""
 echo "Makevars:"
